---
- name: Assure sudo installed
  apt: pkg={{ item }} state=installed
  with_items:
    - sudo

- name: Assure sudo users created
  user: name={{ item.userid }} groups={{ item.group }} state=present append=yes
  with_items: sudo_users

- name: Assure sudo users created and sudo capable
  user: name={{ item.userid }} groups=sudo append=yes
  with_items: sudo_users

- name: Setup passwordless sudo
  template: src=sudoers.j2 dest="/etc/sudoers.d/{{ item.userid }}" owner=root group=root mode=0600
  with_items: sudo_users
